/* Generated By:JJTree: Do not edit this line. ASTAtom.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package aufgabe_2;

public
class ASTAtom extends SimpleNode {
  public ASTAtom(int id) {
    super(id);
  }

  public ASTAtom(RegAusdruck p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RegAusdruckVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4e3ff636887098e675a5f44681c3eac2 (do not edit this line) */
