/* Generated By:JJTree: Do not edit this line. ASTConcat.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTConcat extends SimpleNode {
  public ASTConcat(int id) {
    super(id);
  }

  public ASTConcat(RegAusdruck p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5911a12f1d4e3bffb249ef9066cbc152 (do not edit this line) */
