/* Generated By:JJTree: Do not edit this line. ASTConcat.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package aufgabe_2;

public
class ASTConcat extends SimpleNode {
  public ASTConcat(int id) {
    super(id);
  }

  public ASTConcat(RegAusdruck p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RegAusdruckVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b1fa586b9cec00d29deecbbd46cc52bb (do not edit this line) */
