package aufgabe_2;

/* Generated By:JJTree: Do not edit this line. ASTStar.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStar extends SimpleNode {
  public ASTStar(int id) {
    super(id);
  }

  public ASTStar(RegAusdruck p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=14884870d4c456f631aaedd40f15e291 (do not edit this line) */
