/* Generated By:JavaCC: Do not edit this line. RegAusdruckTreeConstants.java Version 7.0.10 */
public interface RegAusdruckTreeConstants
{
  public int JJTVOID = 0;
  public int JJTOR = 1;
  public int JJTCONCAT = 2;
  public int JJTSTAR = 3;
  public int JJTATOM = 4;


  public String[] jjtNodeName = {
    "void",
    "Or",
    "Concat",
    "Star",
    "Atom",
  };
}
/* JavaCC - OriginalChecksum=0a82ccdd997b19adb63fcae84c51e661 (do not edit this line) */
