/* Generated By:JavaCC: Do not edit this line. RegAusdruckVisitor.java Version 7.0.10 */
package aufgabe_2;

public interface RegAusdruckVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTOr node, Object data);
  public Object visit(ASTConcat node, Object data);
  public Object visit(ASTStar node, Object data);
  public Object visit(ASTAtom node, Object data);
}
/* JavaCC - OriginalChecksum=132c17561764d248f2a99bd33d1695f9 (do not edit this line) */
