/* Generated By:JJTree&JavaCC: Do not edit this line. RegAusdruckConstants.java */
package aufgabe_2;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RegAusdruckConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Char = 1;
  /** RegularExpression Id. */
  int Empty = 2;
  /** RegularExpression Id. */
  int EmptySet = 3;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<Char>",
    "\"\\\"\\\"\"",
    "\"{}\"",
    "\"(\"",
    "\")\"",
    "\"*\"",
    "\"|\"",
    "\" \"",
    "\"\\t\"",
  };

}
