/* Generated By:JavaCC: Do not edit this line. RegAusdruckDefaultVisitor.java Version 7.0.10 */
package aufgabe_2;

public class RegAusdruckDefaultVisitor implements RegAusdruckVisitor{
	
	/**
	 * 
	 * Durch das visitor-Pattern wird der Code deutlich schmaler und die Abhängigkeiten werden reduziert
	 * 
	 * Alternative dazu ist AntLR  
	 * 
	 * @param node
	 * @param data
	 * @return
	 */
	
	// Das Default visit besucht die Kinder
	
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTOr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTConcat node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStar node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAtom node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=30d822f3d44cebb90dba2cbbc0984b04 (do not edit this line) */
