/* Generated By:JavaCC: Do not edit this line. RegAusdruckTreeConstants.java Version 7.0.10 */
package aufgabe_2;

public interface RegAusdruckTreeConstants
{
  public int JJTVOID = 0;
  public int JJTOR = 1;
  public int JJTCONCAT = 2;
  public int JJTSTAR = 3;
  public int JJTATOM = 4;


  public String[] jjtNodeName = {
    "void",
    "Or",
    "Concat",
    "Star",
    "Atom",
  };
}
/* JavaCC - OriginalChecksum=487bb0b5498fd45a886f14e3e141c5b1 (do not edit this line) */
